### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by NyaomiDEV** [NyaomiDEV/Sunamu#1]
Stuff that is not coming
- macOS support
- Spotify Connect (you have the original project for that)
- Fixed Spotify support on Linux (not our issue, but theirs)

Stuff that I am actually willing to do
- Quality of life improvement on UI and UX
- Nothing else

**Comment by NyaomiDEV** [comment]
superseded by #7

**Comment by nodgear** [comment]
Webnowplaying is not a good implementation to be made.
Web browsers are alredy using Linux/Windows playback api and it works perfectly fine for sunamu [from my experience]

That makes spicetify the only candidate left, which alredy works with said API's;
