### ISSUE TITLE
Delayed lyrics

### ISSUE THREAD

**Issue by Seb3thehacker** [NyaomiDEV/Sunamu#11]
When using Jellyfin on the Sonixd client, lyrics lag about half a second behind.

**Comment by NyaomiDEV** [comment]
That's because the position polling happens every half a second! I should make this configurable, indeed...............

**Comment by Seb3thehacker** [comment]
Yeah would solve it! Making it configurable would be perfect. An option to show each line a bit sooner or later might be a good idea in the future too. Are there any files that I can manually change, and then build it again to have a quicker polling speed?

**Comment by NyaomiDEV** [comment]
https://github.com/NyaomiDEV/Sunamu/blob/f8e5201da019f9d2c1cb76f60c18caeb711cc71e/src/main/playbackStatus.ts#L16

**Comment by Seb3thehacker** [comment]
Thank you very much!

**Comment by NyaomiDEV** [comment]
@Seb3thehacker now the poll interval is configurable in the config! Build from Git again or wait for the new release!

If you have other exciting ideas, please share!
If you have the skills required to maintain, please contribute!

**Comment by Seb3thehacker** [comment]
Of course! Thank you! I'm looking forward to trying it.
