### ISSUE TITLE
Support for other lyric proviers?

### ISSUE THREAD

**Issue by Seb3thehacker** [NyaomiDEV/Sunamu#12]
Having the option to choose other providers would be great. I've run in to handful of songs so far that have no lyrics displayed because of NetEase not having them.

**Comment by Seb3thehacker** [comment]
https://github.com/spotDL/spotify-downloader uses genius and musixmatch. Maybe support for genius would help?

**Comment by NyaomiDEV** [comment]
But I added Genius! Maybe it broke...

**Comment by NyaomiDEV** [comment]
@Seb3thehacker 

Commit 9fe255b217018dea33723ac2c95b2580d7cd5b98 democratizes Musixmatch by bringing it in without parasiting on the official app. Sunamu is now able to request a token straight to the API, and therefore you should see it being used more often (on the git package or if building yourself)
