### ISSUE TITLE
Doesn't start on Fedora with Gnome 43.3

### ISSUE THREAD

**Issue by ThraaxSession** [NyaomiDEV/Sunamu#21]
Hi!
I just installed the RPM package and wanted to try it. Just found this error. Can you tell what to do? A missing lib?

![image](https://user-images.githubusercontent.com/3085830/181285087-7baee1d2-7e77-41d2-bd9d-2dbba00e7ba6.png)

**Comment by ThraaxSession** [comment]
It says libvips-cpp.so Cannot open shared object file. File or directory is missing.

**Comment by ThraaxSession** [comment]
```
sudo dnf install vips # did it
```

**Comment by NyaomiDEV** [comment]
Hey! Don't close the issue report just yet!

**Comment by NyaomiDEV** [comment]
Now it can be closed!
