### ISSUE TITLE
App window space too large if lyrics set to false

### ISSUE THREAD

**Issue by horga83** [NyaomiDEV/Sunamu#23]
If one sets the Lyrics to false the app still thinks the window is that large so there is no way to drag it up near the top of the screen.
It would be nice if the app resized if no lyrics used.  I'm using GNOME 42.

**Comment by dd070** [comment]
I'm currently using Linux Mint 20.3 Cinnamon and I have that same problem.

**Comment by NyaomiDEV** [comment]
I can lower the minimum height a bit, though it will look wonky if lyrics are enabled. I need to think this through; I will keep you guys posted

**Comment by NyaomiDEV** [comment]
![image](https://user-images.githubusercontent.com/13177694/181767721-7a188727-26ca-4180-bc57-874077796318.png)

**Comment by horga83** [comment]
I think the default for me is to never show the lyrics so a smaller
window is best but hey, this is your project so....:-)
