### ISSUE TITLE
Widget disappear on windows 11.

### ISSUE THREAD

**Issue by generalpy101** [NyaomiDEV/Sunamu#42]
Hello. I just installed Sunamu in windows 11 and the widget disappears when I open any application and return back to desktop.
I have to click on taskbar( normally where time is shown) so that widget can return. Is this windows 11 only problem? Any resolution.
It absolutely works fine in my Ubuntu and Manjaro distribution. I am using it with Vivaldi Browser and YT music. Vivaldi is chrome based so identification works fine.

**Comment by NyaomiDEV** [comment]
Explain it with a video. It is hard to understand how it is problematic on Windows.

**Comment by NyaomiDEV** [comment]
Not seeing any activity, closing for now.
