### ISSUE TITLE
UI shifted and updates no longer working after sleep

### ISSUE THREAD

**Issue by busybox11** [NyaomiDEV/Sunamu#43]
I was using Sunamu for a bit and then had to do something else, so I left it in the background in one of my tabs.
Later on my laptop went to sleep, and when unlocking it and going back to Sunamu's browser tab, the whole UI shifted to the left and the updates are no longer working (see screenshot)
![image](https://user-images.githubusercontent.com/29630035/183758379-387efbe0-7c4a-44fe-abd3-cacdb5cafcc0.png)
As the devtools suggested, the webserver is no longer accessible, though I don't know if it happened before or after sleep (but my guess is after).
Indeed, Sunamu is nowhere to be found in the task manager.

**Comment by NyaomiDEV** [comment]
I regularly put to sleep and resume my PC without issues; so wtf?!

Please investigate further. I'd ask you about the dmesg but I guess that is late.

**Comment by busybox11** [comment]
Yeah I'm confused too.
It doesn't happen with Linux, this is windows, I can't provide you the dmesg anyway haha.
Will do. I'll keep you updated about that!

**Comment by busybox11** [comment]
Well, looks like part of the problem is browser-related so I'd guess all platforms are affected.
But the fact that the daemon is killed after sleep is prolly a Windows problem indeed. Maybe the whole shifting thing happens because of the inactivity and the fact the daemon was killed... idk, there goes some test ideas I should do whenever I have time.
I cannot test with the built-in electron window since it doesn't show up lol
Gotta troubleshoot that too.

**Comment by NyaomiDEV** [comment]
I cannot fix this issue as I am not using Windows anymore, though, so for now I will consider Windows experimental again until a known cause is known and a fix is proposed.

**Comment by busybox11** [comment]
Indeed.
If you need help with anything, I have a dualbooted Windows/Arch machine.
I'll do some troubleshooting on my own but if you need anything, hmu!

**Comment by NyaomiDEV** [comment]
well the UI shift may be the progressbar going into oblivion and shifting everything with it; while it shouldn't have happened, a css fix may be doable. the problem here though is that sunamu cannot recover from sleep, and I think it's because of the winrt bindings. if it's because of those bindings, I cannot do anything about it.

**Comment by busybox11** [comment]
Can confirm, it's caused by the seekbar. Removing it from the DOM un-shifts the UI, and we also notice that the elapsed time is still going past the length of the song.
![image](https://user-images.githubusercontent.com/29630035/184932127-b1324e46-df29-4b0d-a1f5-a9ec0c46d384.png)

**Comment by NyaomiDEV** [comment]
The UI shifting is fixed in master.

Sunamu closing is not something I can fix, however.

**Comment by NyaomiDEV** [comment]
Look, this is not a Sunamu issue per se. I am closing this as completed as I fixed the shifting inside Sunamu, though WinPlayer-Node could use an issue for the sleep problem.
