### ISSUE TITLE
💀💀 localhost background uses insane resources 💀💀

### ISSUE THREAD

**Issue by HH756** [NyaomiDEV/Sunamu#45]
![image](https://user-images.githubusercontent.com/67608772/185549976-9bcae320-539a-40e6-9286-d015da87668b.png)
Rendering the background pins my CPU near 90%, Turning off the background solves it. Maybe my PC is garbo

**Comment by NyaomiDEV** [comment]
background as in webserver? or the widget mode? please explain yourself better. Also what are your specs?

**Comment by HH756** [comment]
The local-host front-end background.
![image](https://user-images.githubusercontent.com/67608772/185698738-361523ba-6595-4660-93ca-416ebde3b37f.png)
Specs: 
![image](https://user-images.githubusercontent.com/67608772/185698928-da20d3eb-c162-4b3f-bf9d-c0cb3b584b4f.png)
Should have mentioned I'm in a VM.

**Comment by NyaomiDEV** [comment]
You should really use a GPU accelerated environment to use Sunamu. If you are using software rendering that is bound to happen.

There are configuration options to toggle the animation on and off, however.

Closing this as not planned, but feel free to comment further.
