### ISSUE TITLE
Always-on-top Window

### ISSUE THREAD

**Issue by archerindigo** [NyaomiDEV/Sunamu#49]
Hi, thanks for making this great app.

I want to ask whether the window can set as always-on-top?

**Comment by NyaomiDEV** [comment]
If your window manager supports it, then you can set it always on top like you would on any other window, on Linux. Windows 10 and 11 support is experimental and incomplete, and it will not accept any feature requests until a Windows maintainer is found.

**Comment by archerindigo** [comment]
Just found a solution. I am running on Manjaro Gnome, the app has the title bar hidden so I cannot bring up the context menu by mouse. Instead, I can use the keyboard shortcut `alt + space`.

**Comment by archerindigo** [comment]
FYI Windows has an official utility called PowerToys which contains an Always on Top utility. I haven't test it on this app though.
https://docs.microsoft.com/en-us/windows/powertoys/always-on-top
