### ISSUE TITLE
.desktop file invalid

### ISSUE THREAD

**Issue by probonopd** [NyaomiDEV/Sunamu#50]
Thanks for making an AppImage for Linux.

The `sunamu.desktop` file invalid. Please check with `desktop-file-validate`.
https://manpages.ubuntu.com/manpages/bionic/man1/desktop-file-validate.1.html

Reference:
https://github.com/AppImage/appimage.github.io/pull/2986

**Comment by NyaomiDEV** [comment]
Sunamu uses `electron-builder` to build AppImage files. If the `.desktop` file is invalid, it therefore is a problem with `electron-builder` and I cannot really fix it myself.
