### ISSUE TITLE
Option to hide browser source when nothing is playing

### ISSUE THREAD

**Issue by AG4lyf** [NyaomiDEV/Sunamu#52]
Personally used sunamu for a while. and suggested it to a streamer. his complaint was that the widget takes a lot of unused space when nothing is playing in the background. in this case if the option is enabled then "all" of the elements in browser source shall not be rendered.

**Comment by NyaomiDEV** [comment]
Couldn't he just read the configuration file? Sunamu is expected to hide itself when nothing is playing.

**Comment by AG4lyf** [comment]
I myself can't seem to find any option to do so. also it says "please play something" on obs rather than hiding itself. 
I am asking for option to hide the sunamu source on obs when the song is "paused" or nothing is playing.

**Comment by NyaomiDEV** [comment]
it is a browser source and not a plugin. I am not sure how I should tell OBS to hide the source for you. You can toggle it off if you're not using it.

**Comment by AG4lyf** [comment]
i know its a browser souce. but if the query is from a "obs-studio" scene. then don't render anything on the screen "if" the media is currently paused or songdata.metadata.id doesn't exists.

am not asking to hide it from obs. but not render anything. a blank souce.

**Comment by AG4lyf** [comment]
i know its a browser souce. but if the query is from a "obs-studio" scene. then don't render anything on the screen "if" the media is currently paused or songdata.metadata.id doesn't exists.

am not asking to hide it from obs. but not render anything. a blank souce.

**Comment by NyaomiDEV** [comment]
I will take this into consideration, but I will schedule it for the next release.

Do note that this project is not actively maintained and there is no ETA, meaning it can take a lot of time for anything to land.

**Comment by AG4lyf** [comment]
while we are at it. why not add build instructions ?

**Comment by NyaomiDEV** [comment]
It just builds like any other average Electron application, and actually this one is simpler. I feel like there's no real need to put them there.
