### ISSUE TITLE
Check ID3/lrc file for lyrics

### ISSUE THREAD

**Issue by hannahswain** [NyaomiDEV/Sunamu#55]
It's great how many different lyrics Sunamu can find! However, some of them just don't exist (music too new/too niche) or the syncing is wrong. I like adding my own synced lyrics to the ID3/Vorbis tag so that they are correct.

Would you consider checking the file tag, then for a .lrc file, and then checking other online sources?

**Comment by NyaomiDEV** [comment]
Well, if you're on Linux and your media player supports it, your lyric tag already gets read by Sunamu (it just won't read it as a LRC formatted tag, for now).

However, giving Sunamu access to the entire file system is problematic on Flatpak, so I chose to not read any sparse .LRC file at all and this will not change as I don't want people to have to use Flatseal to restrict the scope of Sunamu or mess with its permissions on Linux.

On Windows, given the limitations of the SMTC API, what you ask is essentially impossible.

**Comment by hannahswain** [comment]
Thanks for that background!

I think my situation may be an edge-case then:

* Lyrics saved in the `Lyrics`frame of the Vorbis tag for flac files 
* Music hosted through Navidrome
* Played through Sonixd

I tested yesterday and Sunamu was not using my lyrics - I could tell because they weren't synced while I could see the synced lyrics correctly in another app (Symfonium on Android). 

I wanted to make sure it was on the radar in case anyone else came across it. Thanks again!

**Comment by NyaomiDEV** [comment]
`Sonixd` I believe is not fully compliant and it won't pass lyrics to the MPRIS API.

This said, Sunamu @ git already supports provider re-ordering so that you can put your metadata in front of other services. The part which is NOT there is the LRC interpretation.

**Comment by NyaomiDEV** [comment]
and there you have it, something something

**Comment by hannahswain** [comment]
Lovely,t thank you!
