### ISSUE TITLE
Lyrics not syncing with music

### ISSUE THREAD

**Issue by Pauldb8** [NyaomiDEV/Sunamu#56]
Hello there, 
Thank you for this awesome application. I just downloaded 2.1.0 release as AMD64 deb.

I installed it on my KDE 22.10 linux machine.
I'm using Spotify deb as my player.

The song title and artist are displayed correctly, but not the thumbnail. 
Also the buttons, play pause, previous, next are working fine too.

Nevertheless the lyrics are showing properly but unfortunately they don't follow along with the song.

Also for the first second the playing position bar on the bottom appears, then it disappears, which makes me think that Sunamu is not able to fetch the time related information about the song, hence the time bar disappears, and hence lyrics don't sync.

I've tried checking the configuration, but it is set as default and karaoke: true.
No logs are output when run from the terminal.

If any further info is needed I'll gladly comply.

Thanks,
Paul.

**Comment by NyaomiDEV** [comment]
Spotify is a dodgy client and all issues with the API must be reported to the Spotify developers.

Please use another media player.

**Comment by Pauldb8** [comment]
Ok, that actually pointed me in the right direction. 

Since COMPATIBILIY.md does say Spotify to be supported. I just realized I had a very old version of Spotify deb installed. I actually now added their official repo and upgraded version.

And now it actually works, thumbnail, time information, and lyric sync.

Leaving this here for posterity, thank you.
