### ISSUE TITLE
None of the players seem to work

### ISSUE THREAD

**Issue by isle9** [NyaomiDEV/Sunamu#58]
I've tried AppImage, flatpak and deb and none of them seem to work either.

edit: I'm on Ubuntu 22.10

**Comment by NyaomiDEV** [comment]
Sunamu is not a music player.

**Comment by isle9** [comment]
> Sunamu is not a music player.

I know 😅 .

What I meant is that Sunamu doesn't seem to detect any of the players I used to play music. Lyrics aren't being shown and I get the message to play something.

**Comment by NyaomiDEV** [comment]
Which players do you use?

**Comment by NyaomiDEV** [comment]
Out of everything you're citing, only Spotify on the desktop is supported by Sunamu. Please try it out with that.

**Comment by isle9** [comment]
All of these players worked fine previously when I was using popOS and all of the players seem to expose the API to the system.

Where exactly can I find the logs?
I found some in ~/.config/sunamu, but there is basically nothing in them.

**Comment by isle9** [comment]
[Failed to load module "canberra-gtk-module"](https://askubuntu.com/questions/1175572/how-to-fix-error-failed-to-load-module-canberra-gtk-module)

I forgot to try and run it from the terminal in the first place.
