### ISSUE TITLE
Is there a way to customize the settings?

### ISSUE THREAD

**Issue by JayXYZWasTaken** [NyaomiDEV/Sunamu#61]
I'd like to be able to have an option to make the display not have any lyrics, and for the actual song to always be in the state where you hover over it, not the collapsed view with only the name and time.
If there is some sort of menu that I missed during install let me know. 

I saw your post on your profile saying you won't be active, but I've seen some stuff within the past month, so I'm not sure.
Let me know -
JayXYZ#4037 On Discord

**Comment by NyaomiDEV** [comment]
https://github.com/NyaomiDEV/Sunamu/blob/d03314f52e586c795efd03d7f04532ae43430075/README.md?plain=1#L53-L62

https://github.com/NyaomiDEV/Sunamu/blob/master/assets/config.json5
