### ISSUE TITLE
Follow up- Lyrics disabler

### ISSUE THREAD

**Issue by JayXYZWasTaken** [NyaomiDEV/Sunamu#62]
I had an issue opened before- 
I disabled the "showLyrics:" to false, but I still see all the lyrics? Is there something I missed. I made sure to close the program completely (I just used task manager), and then restart the app.

I also could not find an option to make it so the actual song displayer it never collapsed. I always want it full sized as if I were hovering over it.

**Comment by NyaomiDEV** [comment]
Please read the configuration file carefully, this is not a support section.

Do not open other issues that are NOT issues with the program.
