### ISSUE TITLE
[bug] Error with AppImage on Ubuntu 20.04 + build process ?

### ISSUE THREAD

**Issue by borrougagnou** [NyaomiDEV/Sunamu#73]
Hello,

I have a problem when I try to use the appimage on Ubuntu:
```
$> chmod +x Sunamu-2.2.0/AppImage
$> ./Sunamu-2.2.0/AppImage
[lyricsOffline.js:convertUncompressed:68:23] Cannot convert uncompressed lyrics; probably the cache path does not exist.
[lyricsOffline.js:statCachePath:85:23] Cannot stat lyrics cache path; probably it does not exist.
sunamu: symbol lookup error: /tmp/.mount_SunamumtyBXM/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-linux-x64.node: undefined symbol: vips_fail_on_get_type
```

I don't know what's wrong and how to fix that
on internet, some people said we need to update `npm install sharp@latest`
but with an AppImage I don't know how to do that.

also **question 2**, where I can put the " .lrc / .srt " file ?
I see "local: true" on the config.json but where I can add the "folder location" ?

Regards

**Comment by NyaomiDEV** [comment]
Please refrain from using the same issue ticket to also embed a question.

For starters, what is your Ubuntu version? Check if you have every package up to date. We do not support Ubuntu EOL versions, and we do not support anything "too old" such as Ubuntu 20.04 LTS. If you're on Ubuntu 22.04 LTS or newer, consider getting an up to date version of VIPS, which is a dependency for Sunamu.

Aside from that, you don't need to move your local .LRC files from where they belong (in pair with the tracks you're playing.)
Note that Sunamu does not support SRT files, and you need a compatible local music player to get local lyrics (such as Strawberry Music Player.)

**Comment by borrougagnou** [comment]
Hello,
thank you for your answer,

My Ubuntu version is 20.04 LTS
the "standard EOL" for Ubuntu 20.04 is April 2025

Sad if you don't support anymore this version, actually I can't migrate to 22.04 because of compatibility issue with another program.


Do you have any wiki or complete readme for the build/run process ? Or for the "nedded dependancy" or the NodeJS version ?

**Comment by NyaomiDEV** [comment]
You can try to compile the project yourself, there's no extra steps required as the project is really barebones.

Git clone the repo, then type `yarn && yarn build`. If everything goes right, you'll have a Sunamu build in the `targets/` folder. If it doesn't, you need to update to 22.04.

The Node version I use is 20.
