### ISSUE TITLE
[question][feature?] Lyric (LRC) file ?

### ISSUE THREAD

**Issue by borrougagnou** [NyaomiDEV/Sunamu#74]
This post complete the answer at #73 

>> where I can put the " .lrc / .srt " file ?
>> I see "local: true" on the config.json but where I can add the "folder location" ?

> Aside from that, you don't need to move your local .LRC files from where they belong (in pair with the tracks you're playing.)
> Note that Sunamu does not support SRT files, and you need a compatible local music player to get local lyrics (such as Strawberry Music Player.)

Hello,
thank you for your answer,

What is the "local:true" values for ?
https://github.com/NyaomiDEV/Sunamu/blob/48f99900e2b9e0a7352f6d4d96b19df808f895c5/assets/config.json5#L69C10-L69C10

Because I mean, I have a youtube video, the player can found the title of the music, but there is "no lyric" for that, so, where I need to add the file ?

**Comment by NyaomiDEV** [comment]
`Local: true` only refers to lyric files besides local tracks. You cannot use them with YouTube nor Spotify.
