### ISSUE TITLE
Error: Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by mbnis7** [NyaomiDEV/Sunamu#76]
Sorry in advance as I'm not exactly as well versed in all this as I'd like to believe I am.

I downloaded the AppImage file for Sunamu and found out I couldn't execute it, even after checking if all the permissions were enabled. I then tried to execute it on the terminal (./Sunamu-2.2.0.AppImage) but got this error message:

![Screenshot from 2024-01-30 12-49-07](https://github.com/NyaomiDEV/Sunamu/assets/132301524/c275fc81-2092-46b0-9576-085367b63557)

 - OS: Ubuntu 23.10
 - Node: 20.11.0
 - NPM: 10.2.4

**Comment by NyaomiDEV** [comment]
your download is corrupted, download it again
